server:
  port: 80

spring:
  application:
    name: users-consumer

eureka:
  client:
    service-url:
      defaultZone: http://admin:123@localhost:6001/eureka/
  register-with-eureka: true
  fetch-registry: true
